version: 2
jobs:
  build:
    docker:
      - image: rust:1.31-slim
    steps:
      - checkout
      - restore_cache:
          - keys:
              - target-
              -
      - run:
          name: Build
          command: |
            apt-get update && apt-get install -y libssl-dev pkg-config libpq-dev
            rustup default nightly
            cargo install --path .
            cargo install diesel_cli && diesel setup && diesel migration run

      - save_cache:
          key: target-
          paths: "target"