version: 2
jobs:
  build:
    docker:
      - image: rust:1.31-slim
    steps:
      - checkout
      - restore_cache:
          keys:
              - target-
              - cargo-

      - run:
          name: Build
          command: |
            apt-get update && apt-get install -y libssl-dev pkg-config libpq-dev
            rustup default nightly
            cargo build --release

      - save_cache:
          key: target-
          paths: "target"
      - save_cache:
          key: cargo-
          paths: "~/cargo"