version: 2
jobs:
  build:
    docker:
      - image: rust:1.31-slim
    steps:
      - checkout
      - restore_cache:
          keys:
              - target-
              - target-{.BuildNum.}
              - cargo-
              - cargo-{.BuildNum.}

      - setup_remote_docker:
          docker_layer_caching: true # (3)

      - run:
          name: Build binary
          command: |
            mkdir cargo
            export CARGO_HOME=cargo
            apt-get update && apt-get install -y libssl-dev pkg-config libpq-dev curl openssh-client
            rustup default nightly
            cargo build --release

      - save_cache:
          key: target-{.BuildNum.}
          paths: "target"
      - save_cache:
          key: cargo-{.BuildNum.}
          paths: "cargo"

      - run:
          name: Dockerify & deploy
          command: |
            echo $ID_RSA > circle_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan -H synthetic.services >> ~/.ssh/known_hosts
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
            docker build --file DockerfileBin .
            docker save $(docker images -q | head -1) | ssh circle@synthetic.services -i circle_rsa "dokku tar:in codepaydemo"